# Utilisez la dernière version de Sphinx
version: 2

# Configuration de base, python et autres outils
build:
  os: ubuntu-22.04
  tools:
    python: "3.11.1"

# Construction de la documentation
sphinx:
  configuration: doc/conf.py
