# Generated by Django 3.0 on 2024-01-27 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def data_transfer(apps, schema_editor):
    # Importation des models depuis l'ancienne application
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')

    # Importation des models depuis la nouvelle application
    NewAddress = apps.get_model('lettings', 'Address')
    NewLetting = apps.get_model('lettings', 'Letting')
    NewProfile = apps.get_model('profiles', 'Profile')

    # Récupération de toutes les instances de l'ancien model Address
    old_addresses = OldAddress.objects.all()

    # Transfert des données vers le nouveau model Address
    for old_address in old_addresses:
        # création d'une nouvelle instance du model Address dans la nouvelle application
        new_address = NewAddress(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code,
        )
        new_address.save()
    
    # Récupération de toutes les instances de l'ancien model Letting
    old_lettings = OldLetting.objects.all()

    # Transfert des données vers le nouveau model Letting
    for old_letting in old_lettings:
         # Créez une nouvelle instance de l'adresse pour chaque itération
        new_address = NewAddress.objects.get(number=old_letting.address.number)
        new_letting = NewLetting(
            title=old_letting.title,
            address=new_address,
        )
        new_letting.save()
    
    # Récupération de toutes les instances de l'ancien Profile
    old_profiles = OldProfile.objects.all()

    # Transfert des données vers le nouveau model Profile
    for old_profile in old_profiles:
        # Création d'une nouvelle instance dans la nouvelle application
        new_profile = NewProfile(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city,
        )
        new_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oc_lettings_site', '0001_initial'),
        ('lettings', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(data_transfer)
    ]
