# Generated by Django 3.0 on 2024-01-27 15:50

from django.db import migrations


def delete_datas_old_models(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')

    # Suppression des données des anciens modèles
    OldProfile.objects.all().delete()
    OldAddress.objects.all().delete()
    OldLetting.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20240127_1601'),
    ]

    operations = [
        # Appel à la fonction pour supprimer les données des anciens modèles
        migrations.RunPython(delete_datas_old_models),

        # Suppression des models et champs associés de oc_lettings_site
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
