name: CI/CD - Pipeline

# Déclencheurs : exécute la pipeline sur les push et pull requests sur la branche main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Configuration de l'environnement d'exécution (Ubuntu latest, Python 3.11.1)
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "thomassavelli/lettings_p13"
    strategy:
      matrix:
        python-version: [3.11.1]

    steps:
    # Étape pour récupérer le code source
    - uses: actions/checkout@v3
    # Étape pour configurer Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Étape pour installer les dépendances 
    - name: Install Dependencies
      id: dependencies-installing
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape pour créer et définir les variables d'environnement
    - name: Creates and sets environment variables
      id: dot_env
      run: |
        echo "DSN=${{ secrets.DSN }}" > .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
      if: ${{ steps.dependencies-installing.outcome }} == "success"
    
    # Étape pour exécuter le linter (flake8)
    - name: Run Linting
      id: linting
      run: |
        flake8 .
      if: ${{ steps.dot_env.outcome }} == "success"

    # Étape pour exécuter les tests    
    - name: Run Tests
      id: tests
      run: |
        pytest --ignore=env
      if: ${{ steps.linting.outcome }} == "success"

    # Étape pour s'assurer que la couverture des tests est supérieure à 80%    
    - name: Ensures test coverage is above 80%
      id: coverage_test
      run: |
        pytest --cov-fail-under=80
      if: ${{ steps.tests.outcome }} == "success"
    
    # Connection à Dockerhub
    - name: Dockerhub Login
      id: dockerhub-login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      if: ${{ steps.coverage_test.outcome }} == "success" 

    # Construction et push de l'image Docker
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.IMAGE_NAME }}:latest
      if: ${{ steps.dockerhub-login.outcome }} == "success"

    - name: Install Render CLI
      id: Render_CLI
      run: |
        # installations directes pour tous les systèmes d'exploitation pris en charge
        curl -LJO https://github.com/render-oss/render-cli/releases/latest/download/render
        chmod +x render
        sudo mv render /usr/local/bin/render
      if: ${{ steps.docker_build.outcome }} == "success"

    - name: Trigger Render Deployment
      run: |
        # Déclenchement du déploiement automatique sur Render du service oc_lettings
        # en utilisant le Render CLI installé précédemment
        /usr/local/bin/render deploy --service oc_lettings
      if: ${{ steps.Render_CLI.outcome }} == "success"
